language: node_js
os:
  - windows
env:
  - MOZ_HEADLESS=1
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; choco install firefox; export FIREFOX_BINARY="/c/Program Files/Mozilla Firefox/firefox.exe"; export CHROME_BINARY="/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"; env; fi
script:
  - npm run coverage
  - npm run test-chrome
  - npm run test-firefox
