language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install:
  - powershell ./downloadChrome.ps1
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then .\chrome64_67.0.3396.79.exe /silent /install; fi
script:
  - npm run test-chrome
