language: node_js
os:
  - windows
env:
  - MOZ_HEADLESS=1
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; choco install firefox; cd "C:\Program Files\Mozilla Firefox"; echo "firefox directory"; pwd; dir; fi
script:
  - npm run coverage
