language: node_js
os:
  - windows
env:
  - MOZ_HEADLESS=1
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then pwd; cd "/c/Program Files (x86)/Google/Chrome/Application/70.0.3538.110"; dir; cd "/c/Program Files/Mozilla Firefox"; dir; fi
script:
  - npm run coverage
