language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install chromium --pre -y; cd "C:\Program Files (x86)\Chromium\Application"; chrome --headless --disable-gpu --dump-dom --enable-logging https://www.chromestatus.com/ --no-first-run; fi
script:
  - npm run test-chrome
