language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine; powershell ./downloadChrome.ps1; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ".\chrome64_67.0.3396.79.exe /silent /install"; echo "Sleeping for 30 seconds to allow install"; powershell sleep -s 30; cd "C:\Program Files (x86)\Google\Chrome\Application"; pwd; dir; echo "after this comes the call to chrome"; .\chrome --headless --disable-gpu --dump-dom --enable-logging https://www.chromestatus.com/ --no-first-run; fi
script:
  - npm run test-chrome
