language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine; powershell ./downloadChrome.ps1; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "starting path:"; pwd; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ".\chrome64_67.0.3396.79.exe /silent /install"; echo "Sleeping for 30 seconds to allow install"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell sleep -s 30; cd "C:\Program Files (x86)\Google\Chrome\Application"; pwd; dir; echo "after this comes the call to chrome"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ".\chrome --headless --remote-debugging-port=9333 --enable-logging"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd "C:\\Users\\travis\\build\\techrev\\teddy"; fi
script:
  - npm run test-chrome
 after_script:
   - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Get-CimInstance -ClassName Win32_Process -Filter "CommandLine LIKE '%chrome.exe%--headless%'" | %{Stop-Process $_.ProcessId}; fi
