language: node_js
os:
  - windows
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; choco install firefox; fi
script:
  - npm run coverage
  - npm run test-chrome
  - npm run test-firefox
