language: node_js
os:
  - windows
env:
  - MOZ_HEADLESS=1
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; choco install firefox; pwd; fi
script:
  - npm run coverage
  - karma start karma.conf.js
