language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install chromium --pre -y; fi
script:
  - npm run coverage
  - npm run test-chrome
