language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine; powershell ./downloadInstallChrome.ps1; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./startChrome.ps1 fi
script:
  - npm run test-chrome
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./stopProcesses.ps1; fi
