language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install: # the sleep is to give it time to install. Otherwise it keeps going before the installer has a chance to finish
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine; powershell ./downloadInstallChrome.ps1; powershell sleep -s 30; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then  cd "C:\Program Files (x86)\Google\Chrome\Application"; pwd; dir; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd "C:\\Users\\travis\\build\\techrev\\teddy"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./startChrome.ps1; fi
script:
  - npm run test-chrome
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./stopProcesses.ps1; fi
