language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine; powershell Get-ExecutionPolicy -List; fi
script:
  - npm run test-chrome
